Repository hudiM/ask-mate-python, pull requests merged in 2019-01, with the labels that each got.

#2 tags feature
  data_manager.py
  server.py
  templates/navigation.html
  templates/tags.html
Labels: enhancement

#5 Rework
  data_manager.py
  server.py
  static/avatars/2x (17).gif
  static/avatars/2x (3).gif
  static/avatars/2x (5).png
  static/avatars/2x_13.gif
  static/avatars/2x_16.gif
  static/avatars/2x_25.gif
  static/avatars/default.png
  static/css/main.css
  static/images/Checkmark.png
  templates/list.html
  templates/navigation.html
  templates/new_answer.html
  templates/new_question.html
  templates/question.html
  templates/registration.html
Labels: bug, enhancement

#4 Feature user list
  data_manager.py
  server.py
  static/images/Calendar.png
  static/images/Reputation Badge.png
  templates/navigation.html
  templates/users.html
Labels: enhancement

#6 Hotfix
  templates/question.html
  templates/users.html
Labels: bug

#7 User display fix
  data_manager.py
  server.py
  static/avatars/2x (10).png
  static/avatars/2x (17).gif
  static/avatars/2x (3).gif
  static/avatars/2x (5).png
  static/avatars/2x_13.gif
  static/avatars/2x_16.gif
  static/avatars/2x_25.gif
  static/avatars/default.png
  static/css/main.css
  static/images/Calendar.png
  static/images/Checkmark.png
  static/images/Reputation Badge.png
  templates/list.html
  templates/navigation.html
  templates/new_answer.html
  templates/new_question.html
  templates/question.html
  templates/registration.html
  templates/tags.html
  templates/users.html
Labels: bug, enhancement

#9 bind questions to user
  data_manager.py
  server.py
Labels: enhancement

#10 feature user page
  data_manager.py
  server.py
  static/css/main.css
  templates/layout_user.html
  templates/navigation.html
  templates/user.html
Labels: enhancement

#11 bind_comment done
  data_manager.py
  server.py
Labels: enhancement

#12 reputation system done
  data_manager.py
  server.py
Labels: enhancement
